@host= http://localhost/5056/
@token = eyJUHygvb5uvTFGVBtgYIHgyGYObyGYhUHuihUGyg7GyGH7ggtFUiYt6TYIytfgvTgtyGuG

@hostId =asdf
POST {{host}}/{{hostId}}/menus

Content-type : application/json
Authorization: Bearer {token}


{
"name" : "Wale's Delicious Snack Menu",
"description" : "A snack menu made by wale that is delicious and tanterlising",
"averageRating" :4.5,
"sections" : {
    "id":"00000000000-0000000-00000-00000-000000000000000000",
    "name": "Appetizers",
    "description": "Starting snack",
    "items" :{
       "id" : "00000000000-0000000-00000-00000-000000000000000000",
       "name": "Fried eggs and Okra"
       "description": "Well seasoned fried eggs spiced with sugar combined with drawing okra soup",
       "price": 5000
      } 
      
}

}

