///<auto-generated>

using System;
using Snacker.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Snacker.Infrastructure.Migrations
{
    [DbContext(typeof(SnackerDbContext))]

    partial class SnackerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
  #pragma warning disable 612,618
          modelBuilder
          .HasAnnotation("ProductVersion","7.0.1")
          .HasAnnotation("Relational:MaxidentifierLength",100)

        }
    }
}